# Generated by Django 4.1.1 on 2022-09-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattes', models.IntegerField()),
                ('poids', models.IntegerField()),
                ('taille', models.IntegerField()),
                ('vitesse', models.IntegerField()),
                ('famille', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
            ],
        ),
    ]
